from typing import Any, Optional

from botocore.awsrequest import AWSResponse as AWSResponse
from botocore.exceptions import ParamValidationError as ParamValidationError
from botocore.exceptions import StubAssertionError as StubAssertionError
from botocore.exceptions import StubResponseError as StubResponseError
from botocore.exceptions import UnStubbedResponseError as UnStubbedResponseError
from botocore.validate import validate_parameters as validate_parameters

class _ANY:
    def __eq__(self, other: Any) -> Any: ...
    def __ne__(self, other: Any) -> Any: ...

ANY: Any

class Stubber:
    client: Any = ...
    def __init__(self, client: Any) -> None: ...
    def __enter__(self) -> Any: ...
    def __exit__(
        self, exception_type: Any, exception_value: Any, traceback: Any
    ) -> None: ...
    def activate(self) -> None: ...
    def deactivate(self) -> None: ...
    def add_response(
        self, method: Any, service_response: Any, expected_params: Optional[Any] = ...
    ) -> None: ...
    def add_client_error(
        self,
        method: Any,
        service_error_code: str = ...,
        service_message: str = ...,
        http_status_code: int = ...,
        service_error_meta: Optional[Any] = ...,
        expected_params: Optional[Any] = ...,
        response_meta: Optional[Any] = ...,
    ) -> None: ...
    def assert_no_pending_responses(self) -> None: ...
